### GET
GET http://localhost:5008/

###

### GET steden
GET http://localhost:5008/steden

###

### GET alle weerstations
GET http://localhost:5008/weerstations

###

### GET alle metingen
GET http://localhost:5008/metingen

###

### GET weerbericht
GET http://localhost:5008/weerbericht

###

### Laat alle stations een meting genereren
POST http://localhost:5008/commands/metingen

###

//TODO api tests aanvullen